// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryvcibvfprtrfxstenpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5dmNpYnZmcHJ0cmZ4c3RlbnBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxODk3MzMsImV4cCI6MjA3Mzc2NTczM30.eYYKRvxL9g1ZgpGX_KL2kUDP_v7rIDWtdwMP2MDlvMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});